### ISSUE TITLE
LangChain: `cratedb_rag_customer_support.ipynb` trips with `CellTimeoutError`

### ISSUE THREAD

**Issue by amotl** [crate/cratedb-examples#297]
## Problem

`cratedb_rag_customer_support.ipynb` has been introduced just recently.

It looks like the call to `embeddings.embed_documents(pages_text)` might take longer than expected / uses more compute resources / stalls for any other reasons?
```python
E           nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 120 seconds.
E           The message was: Cell execution timed out.
E           Here is a preview of the cell contents:
E           -------------------
E           embeddings = OpenAIEmbeddings(deployment='my-embedding-model', chunk_size=1)
E           pages_embeddings = embeddings.embed_documents(pages_text)
E           -------------------

/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/nbclient/client.py:801: CellTimeoutError
------------------------------ Captured log call -------------------------------
ERROR    pytest_notebook.execution:client.py:795 Timeout waiting for execute reply (120s).
```

-- https://github.com/crate/cratedb-examples/actions/runs/7881120885/job/21504241805#step:6:848

## Q & A

Can you dig a bit into this, @marijaselakovic? Do you have any idea where this may be coming from, or how it can be improved?

NB: It's not a unique thing. We are also taking care about the same details at GH-170 and GH-299.

**Comment by marijaselakovic** [comment]
Fixed here: https://github.com/crate/cratedb-examples/pull/303

**Comment by amotl** [comment]
Thanks!
