### ISSUE TITLE
Issue with time series forecasting with pycaret notebook

### ISSUE THREAD

**Issue by marijaselakovic** [crate/cratedb-examples#365]
When running `automl_timeseries_forecasting_with_pycaret.ipynb` notebook the `mlflow-cratedb` module gets installed but it is not found when importing:

```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-c9198aa96905>](https://localhost:8080/#) in <cell line: 6>()
      4 import plotly
      5 import plotly.graph_objects as go
----> 6 import mlflow_cratedb  # Required to enable the CrateDB MLflow adapter.
      7 from dotenv import load_dotenv
      8 

ModuleNotFoundError: No module named 'mlflow_cratedb'
```
Can you check/test the code? The issue persists both locally and in Colab.

**Comment by amotl** [comment]
[CI says it works](https://github.com/crate/cratedb-examples/actions/runs/8246941486/job/22554060928#step:6:943), so the flaw might be on your local environment and/or on Colab.

Maybe some error can be observed while installing the packages? To check what might go wrong, just create a separate throw-away virtualenv and probe if the installation works, or channel back any error messages. Thanks!
```
pip install mlflow-cratedb
python
```
```python
>>> import mlflow_cratedb
```

**Comment by marijaselakovic** [comment]
I created a fresh virtual environment, but the only solution I found so far is installing the package with `%pip install mlflow_cratedb` command. For some reason, the package wasn't visible in the notebook.
