### ISSUE TITLE
timeseries-queries-and-visualization.ipynb - Loading initial data doesnt return output

### ISSUE THREAD

**Issue by wierdvanderhaar** [crate/cratedb-examples#479]
The loading of data doesnt return the output that is described. 

`The result contains information about the successfully written rows and potential errors that might have occurred. The output is expected to look roughly like this:

[({'id': '<SOME_ID>', 'name': '<SOME_NAME>'},
  'https://github.com/crate/cratedb-datasets/raw/main/cloud-tutorials/data_weather.csv.gz', 70000, 0, {} )]
The response indicates that 70,000 records have been successfully loaded and that no errors happened.'

My suggestion would be to fully get rid of this piece of text as this doesn't match the reality.

**Comment by amotl** [comment]
Thanks. 62cf293ae87 will get rid of this cell.
