### ISSUE TITLE
apache-kafka-flink-streaming issues

### ISSUE THREAD

**Issue by wierdvanderhaar** [crate/cratedb-examples#508]
# application/apache-kafka-flink-streaming

The create table in the code is not correct, as Flink is ingesting Location and Condition and not inserted_at.

So either the create table should be changed to:

``` SQL
CREATE TABLE IF NOT EXISTS "doc"."weather_flink_sink" (
  "location" OBJECT(DYNAMIC),
  "current" OBJECT(DYNAMIC)
)
```

Or like we change inserted_at into a generated column.

``` SQL
CREATE TABLE IF NOT EXISTS "doc"."weather_flink_sink" (
  "inserted_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL GENERATED ALWAYS AS now(),
  "location" OBJECT(DYNAMIC),
  "current" OBJECT(DYNAMIC)
);
```

**Comment by amotl** [comment]
Hi, and thanks for the report. Can you submit a corresponding adjustment, or can you do it, @surister?

**Comment by amotl** [comment]
Hi. I think this has been fixed with GH-509, right? Thanks!
