### ISSUE TITLE
Check https://cratedb.com/blog/use-cratedb-with-datagrip-an-advanced-database-ide

### ISSUE THREAD

**Issue by surister** [crate/cratedb-examples#682]
Check if https://cratedb.com/blog/use-cratedb-with-datagrip-an-advanced-database-ide still relevant and works. 

Potentially either fix this link or update with new mirror https://bintray.com/crate/crate/crate-jdbc/2.4.0

**Comment by kneth** [comment]
The connection URL in the guide must be changed to `jdbc:crate://localhost:5432/`

**Comment by kneth** [comment]
The blog post has been updated
